### ISSUE TITLE
Enhance Logging

### ISSUE THREAD

**Issue by jmvogt** [jmvogt/EverQuest.GuildBot#18]
1. Start using something like the logger framework so we can set log levels on each message (debug, info, warn, error, etc)
2. Write output to a file only OR in addition to console
3. Ability to configure log level

**Comment by Gishe** [comment]
Going to try to do this on the weekend.

**Comment by jmvogt** [comment]
Ah shoot. Just saw this comment :( I think I ended up opening a PR for this that weekend so that we could have an audit trail for Sunday's raid. 😁 Sorry about that.
